### PR TITLE
Speed up webpack build

### PR DESCRIPTION
**Pull request by bru02**
Implement #44

### CODE REVIEW

**Comment by KaelWD** [comment]
We had a lower-maintenance version of this previously: 3fea8827968d3464ecc9872fc8ef5f8bfb66093b

It may cause css problems as there is no longer a defined import order.

**Comment by kevinmarrec** [comment]
@KaelWD It looks like that since your previous lower-maintenance version, you made import sorted (https://github.com/vuetifyjs/vuetify-loader/blob/master/lib/loader.js#L31) could it prevent any css issue ?

I don't know much about the importance of css import orders but webpack build definitely need speed up, as for now whatever you're using webpack will still look for all components which means also all of their SASS files and that's too heavy extra processing.

**Comment by KaelWD** [comment]
> made imports sorted 

That was to fix https://github.com/vuetifyjs/vuetify/issues/5271, didn't work

We do still have ordering problems (https://github.com/vuetifyjs/vuetify/issues/3583) so maybe it won't be a problem. Either way I'd prefer to use my original code without hard-coded workarounds, we added structures to the vuetify repo specifically for this reason.

**Comment by kevinmarrec** [comment]
@KaelWD I totally agree around the added structures, but something that is annoying is that Webpack seems to just go crazy and load everything when you simply do `impport { VBtn } from 'vuetify/lib'`.

For a little project which use only few components, ther's probably 80% unwanted webpack processing (lot of reached files which will be never used, it includes the loading and processing of unwanted SASS files of all components).

I think the issue has something to do with exports somewhere.

**Comment by KaelWD** [comment]
I'm referring to 3fea882 of course

Webpack processes everything and marks what's actually unused, then the minifier actually removes unused code.

**Comment by kevinmarrec** [comment]
Oh alright, I thought it was a performance issue (seeing all the Vuetify file names processed in Webpack bar progress)

**Comment by KaelWD** [comment]
Thanks for taking the time to do this @bru02. I've merged it into a feature branch for now because there's some changes I want to make before release.

**Comment by johnleider** [comment]
Is this still something you are pursuing @KaelWD ?

**Comment by KaelWD** [comment]
No, it was released in 1.3

**Pull request merged**
