### PR TITLE
fix: make vuetify-loader compatible with @vue/cli 4.1.0-beta.0

### PR DESCRIPTION
**Pull request by DRoet**
Starting from `"@vue/cli": "4.1.0-beta.0",` the vue-loader rule is now a full path instead of just a string. this is due to compatibility w/ yarn V2.

reference: https://github.com/vuejs/vue-cli/issues/4821

### CODE REVIEW

**Comment by DRoet** [comment]
@KaelWD updated using ident, much cleaner.

mind publishing this as 1.3.2? before people start to upgrade and complain 😅

**Comment by pintoflager** [comment]
I got this error with fresh install following instructions in vuetify @ quick start: 
```
yarn run v1.17.3
$ vue-cli-service serve
 INFO  Starting development server...
 ERROR  TypeError: Cannot read property 'match' of undefined
TypeError: Cannot read property 'match' of undefined
    at VuetifyLoaderPlugin.apply (/var/www/html/test/node_modules/vuetify-loader/lib/plugin.js:28:29)
....
```
Checking the existence of the options in plugin.js costructor fixes the problem but I'm just wondering where those options should come from and why they are left undefined.

```
constructor (options) {
    this.options = (options) ? options : {}
  }
```

**Comment by tomcoonen** [comment]
This seems to break compatibility, version 1.4.1 is working fine here (Vue CLI 4.0.5). 
Version 1.4.2 is giving issues: https://github.com/vuetifyjs/vuetify-loader/issues/49#issuecomment-558091210 .

**Comment by ibakhsh** [comment]
Hey, Thanks for the awesome plugin ... 
I am still facing the same isseue: 
```
λ npm run dev

> @ dev c:\Apache24\htdocs\evai
> node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

c:\Apache24\htdocs\evai\node_modules\webpack-cli\bin\cli.js:281
                                throw err;
                                ^

Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.
Make sure there is at least one root-level rule that uses vue-loader.
    at VuetifyLoaderPlugin.apply (c:\Apache24\htdocs\evai\node_modules\vuetify-loader\lib\plugin.js:19:13)
    at webpack (c:\Apache24\htdocs\evai\node_modules\webpack\lib\webpack.js:51:13)
    at processOptions (c:\Apache24\htdocs\evai\node_modules\webpack-cli\bin\cli.js:272:16)
    at yargs.parse (c:\Apache24\htdocs\evai\node_modules\webpack-cli\bin\cli.js:364:3)
    at Object.parse (c:\Apache24\htdocs\evai\node_modules\webpack-cli\node_modules\yargs\yargs.js:567:18)
    at c:\Apache24\htdocs\evai\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (c:\Apache24\htdocs\evai\node_modules\webpack-cli\bin\cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (c:\Apache24\htdocs\evai\node_modules\webpack\bin\webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\i-bak\AppData\Roaming\npm-cache\_logs\2019-11-25T17_49_13_190Z-debug.log
```
i had to stop use vuetify-loader for now just to be able to make the app working again 

my package.js: 
```
"dependencies": {
    "@vue/component-compiler-utils": "^2.0.0",
    "bootstrap": "^4.3.1",
    "bootstrap-datepicker": "^1.8.0",
    "jquery-ui": "^1.12.1",
    "loader-utils": "^1.1.0",
    "popper.js": "^1.15.0",
    "vue-hot-reload-api": "^2.3.0",
    "vue-select": "^3.0.2",
    "vue-style-loader": "^4.1.0",
    "vuetify": "^2.1.10",
    "world-calendars": "^1.0.3"
  },
  "devDependencies": {
    "@babel/cli": "^7.7.0",
    "@babel/core": "^7.7.2",
    "@babel/preset-env": "^7.7.1",
    "axios": "^0.19.0",
    "babel-core": "^6.26.3",
    "babel-loader": "^8.0.4",
    "babel-preset-env": "^1.7.0",
    "bootstrap-sass": "^3.3.7",
    "cross-env": "^5.2.0",
    "css-loader": "^3.2.0",
    "datatables.net": "^1.10.19",
    "datatables.net-dt": "^1.10.19",
    "deepmerge": "^4.2.2",
    "fibers": "^4.0.2",
    "file-loader": "^1.1.11",
    "jquery": "^3.1.0",
    "jquery-slimscroll": "^1.3.8",
    "laravel-mix": "^5.0.0",
    "lodash": "^4.16.2",
    "metismenu": "^2.7.9",
    "node-sass": "^4.11.0",
    "postcss-loader": "^3.0.0",
    "raw-loader": "^0.5.1",
    "resolve-url-loader": "^2.3.1",
    "sass": "^1.23.6",
    "sass-loader": "^8.0.0",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.1",
    "ts-loader": "^4.2.0",
    "url-loader": "^1.0.1",
    "vue": "^2.5.21",
    "vue-cli-plugin-vuetify": "^2.0.2",
    "vue-template-compiler": "^2.5.21",
    "vuetify-loader": "^1.4.2",
    "webpack": "^4.28.3"
  },
  "peerDependencies": {
    "css-loader": "*",
    "webpack": "^4.1.0",
    "vue-template-compiler": "^2.5.16"
  }
```

**Comment by DRoet** [comment]
@ibakhsh it seems like you are missing `vue-loader` in your devDependencies

**Comment by SuperDJ** [comment]
https://github.com/vuetifyjs/vuetify-loader/issues/49 might be related. I had the same issue and downgrading` "vuetify-loader": "^1.4.2"` to `"vuetify-loader": "^1.4.1"` also worked for me

**Comment by ibakhsh** [comment]
@DRoet  added it and still the same issue: 
now package.json: 
```
"dependencies": {
    "@vue/component-compiler-utils": "^3.0.2",
    "bootstrap": "^4.3.1",
    "bootstrap-datepicker": "^1.8.0",
    "jquery-ui": "^1.12.1",
    "loader-utils": "^1.1.0",
    "popper.js": "^1.15.0",
    "vue": "^2.6.10",
    "vue-select": "^3.2.0",
    "vue-style-loader": "^4.1.2",
    "vuetify": "^2.1.10",
    "world-calendars": "^1.0.3"
  },
  "devDependencies": {
    "@babel/cli": "^7.7.0",
    "@babel/core": "^7.7.2",
    "@babel/preset-env": "^7.7.1",
    "axios": "^0.19.0",
    "babel-core": "^6.26.3",
    "babel-loader": "^8.0.4",
    "babel-preset-env": "^1.7.0",
    "bootstrap-sass": "^3.3.7",
    "cross-env": "^5.2.0",
    "css-loader": "^3.2.0",
    "datatables.net": "^1.10.19",
    "datatables.net-dt": "^1.10.19",
    "deepmerge": "^4.2.2",
    "fibers": "^4.0.2",
    "file-loader": "^1.1.11",
    "jquery": "^3.1.0",
    "jquery-slimscroll": "^1.3.8",
    "laravel-mix": "^5.0.0",
    "lodash": "^4.16.2",
    "metismenu": "^2.7.9",
    "node-sass": "^4.11.0",
    "postcss-loader": "^3.0.0",
    "raw-loader": "^0.5.1",
    "resolve-url-loader": "^2.3.1",
    "sass": "^1.23.6",
    "sass-loader": "^8.0.0",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.1",
    "ts-loader": "^4.2.0",
    "url-loader": "^1.0.1",
    "vue-cli-plugin-vuetify": "^2.0.2",
    "vue-loader": "^15.7.2",
    "vue-template-compiler": "^2.5.21",
    "vuetify-loader": "^1.4.2",
    "webpack": "^4.28.3"
  },
  "peerDependencies": {
    "css-loader": "*",
    "webpack": "^4.1.0",
    "vue-template-compiler": "^2.5.16"
  }
```
the error: 
```
 npm run dev

> @ dev c:\Apache24\htdocs\evai
> node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

c:\Apache24\htdocs\evai\node_modules\webpack-cli\bin\cli.js:281
                                throw err;
                                ^

Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.
Make sure there is at least one root-level rule that uses vue-loader.
    at VuetifyLoaderPlugin.apply (c:\Apache24\htdocs\evai\node_modules\vuetify-loader\lib\plugin.js:19:13)
    at webpack (c:\Apache24\htdocs\evai\node_modules\webpack\lib\webpack.js:51:13)
    at processOptions (c:\Apache24\htdocs\evai\node_modules\webpack-cli\bin\cli.js:272:16)
    at yargs.parse (c:\Apache24\htdocs\evai\node_modules\webpack-cli\bin\cli.js:364:3)
    at Object.parse (c:\Apache24\htdocs\evai\node_modules\webpack-cli\node_modules\yargs\yargs.js:567:18)
    at c:\Apache24\htdocs\evai\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (c:\Apache24\htdocs\evai\node_modules\webpack-cli\bin\cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (c:\Apache24\htdocs\evai\node_modules\webpack\bin\webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\i-bak\AppData\Roaming\npm-cache\_logs\2019-11-27T16_16_32_691Z-debug.log
```

**Comment by KaelWD** [comment]
@ibakhsh please add `compiler => { console.log(JSON.stringify(compiler.options.module.rules, null, 2)) }` to the plugins array and show me the output.

**Comment by gl-pasci** [comment]
@KaelWD hi! I'm getting the same error. [These are my webpack rules](https://gist.github.com/gl-pasci/a32c62dd6cc5c41ee7c0017ead1f4450)

The error

```
Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.
Make sure there is at least one root-level rule that uses vue-loader.
    at VuetifyLoaderPlugin.apply (/home/me/Dev/deals/src/node_modules/vuetify-loader/lib/plugin.js:19:13)
    at webpack (/home/me/Dev/deals/src/node_modules/webpack/lib/webpack.js:51:13)
    at processOptions (/home/me/Dev/deals/src/node_modules/webpack-cli/bin/cli.js:272:16)
    at /home/me/Dev/deals/src/node_modules/webpack-cli/bin/cli.js:364:3
    at Object.parse (/home/me/Dev/deals/src/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /home/me/Dev/deals/src/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/me/Dev/deals/src/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/me/Dev/deals/src/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1143:12)
    at internal/main/run_main_module.js:16:11
```

**Comment by KaelWD** [comment]
And that's *after* `new VueLoaderPlugin()`? What version of vue-loader do you have? (`yarn why vue-loader`)

**Comment by gl-pasci** [comment]
I get the error with vuetify-loader@1.4.2 and vue-loader@15.7.2

No errors with 1.3.1 + 15.7.2

**Comment by ibakhsh** [comment]
@KaelWD  ok here its: 

```
[
  {
    "use": [
      {
        "options": {},
        "ident": "ref--0",
        "loader": "c:\\Apache24\\htdocs\\evai\\node_modules\\vue-loader\\lib\\loaders\\pitcher.js"
      }
    ]
  },
  {
    "use": [
      {
        "loader": "html-loader"
      }
    ]
  },
  {
    "use": [
      {
        "options": {
          "publicPath": "/"
        },
        "ident": "ref--1-0",
        "loader": "file-loader"
      },
      {
        "options": {
          "enabled": true,
          "gifsicle": {},
          "mozjpeg": {},
          "optipng": {},
          "svgo": {}
        },
        "ident": "ref--1-1",
        "loader": "img-loader"
      }
    ]
  },
  {
    "use": [
      {
        "options": {
          "publicPath": "/"
        },
        "ident": "ref--2",
        "loader": "file-loader"
      }
    ]
  },
  {
    "use": [
      {
        "options": {
          "name": "[name].[ext]?[hash]",
          "publicPath": "/"
        },
        "ident": "ref--3",
        "loader": "file-loader"
      }
    ]
  },
  {
    "use": [
      {
        "options": {
          "presets": [
            "c:\\Apache24\\htdocs\\evai\\node_modules\\@babel\\preset-env\\lib\\index.js"
          ],
          "plugins": [
            "c:\\Apache24\\htdocs\\evai\\node_modules\\@babel\\plugin-syntax-dynamic-import\\lib\\index.js",
            "c:\\Apache24\\htdocs\\evai\\node_modules\\@babel\\plugin-proposal-object-rest-spread\\lib\\index.js",
            [
              "c:\\Apache24\\htdocs\\evai\\node_modules\\@babel\\plugin-transform-runtime\\lib\\index.js",
              {
                "helpers": false
              }
            ]
          ],
          "cacheDirectory": true
        },
        "ident": "ref--4-0",
        "loader": "babel-loader"
      }
    ]
  },
  {
    "use": [
      {
        "options": {
          "id": 1,
          "omit": 1,
          "remove": true
        },
        "ident": "ref--5-0",
        "loader": "c:\\Apache24\\htdocs\\evai\\node_modules\\extract-text-webpack-plugin\\dist\\loader.js"
      },
      {
        "loader": "style-loader"
      },
      {
        "options": {
          "url": true,
          "sourceMap": false,
          "importLoaders": 1
        },
        "ident": "ref--5-2",
        "loader": "css-loader"
      },
      {
        "options": {
          "sourceMap": true,
          "ident": "postcss0",
          "plugins": [
            null
          ]
        },
        "ident": "postcss0",
        "loader": "postcss-loader"
      },
      {
        "options": {
          "sourceMap": true,
          "engine": "rework"
        },
        "ident": "ref--5-4",
        "loader": "resolve-url-loader"
      },
      {
        "options": {
          "sassOptions": {
            "precision": 8,
            "outputStyle": "expanded"
          },
          "implementation": {
            "info": "node-sass\t4.12.0\t(Wrapper)\t[JavaScript]\r\nlibsass  \t3.5.4\t(Sass Compiler)\t[C/C++]",
            "types": {},
            "TRUE": {},
            "FALSE": {},
            "NULL": {}
          },
          "sourceMap": true
        },
        "ident": "ref--5-5",
        "loader": "sass-loader"
      }
    ]
  },
  {
    "use": [
      {
        "options": {
          "id": 1,
          "omit": 1,
          "remove": true
        },
        "ident": "ref--6-0",
        "loader": "c:\\Apache24\\htdocs\\evai\\node_modules\\extract-text-webpack-plugin\\dist\\loader.js"
      },
      {
        "loader": "style-loader"
      },
      {
        "options": {
          "importLoaders": 1
        },
        "ident": "ref--6-2",
        "loader": "css-loader"
      },
      {
        "options": {
          "plugins": [
            null
          ]
        },
        "ident": "ref--6-3",
        "loader": "postcss-loader"
      }
    ]
  },
  {
    "use": [
      {
        "options": {
          "id": 1,
          "omit": 1,
          "remove": true
        },
        "ident": "ref--7-0",
        "loader": "c:\\Apache24\\htdocs\\evai\\node_modules\\extract-text-webpack-plugin\\dist\\loader.js"
      },
      {
        "loader": "style-loader"
      },
      {
        "loader": "css-loader"
      },
      {
        "options": {
          "plugins": [
            null
          ]
        },
        "ident": "ref--7-3",
        "loader": "postcss-loader"
      },
      {
        "options": {
          "sassOptions": {
            "precision": 8,
            "outputStyle": "expanded"
          },
          "implementation": {
            "info": "dart-sass\t1.23.6\t(Sass Compiler)\t[Dart]\ndart2js\t2.6.1\t(Dart Compiler)\t[Dart]",
            "types": {}
          }
        },
        "ident": "ref--7-4",
        "loader": "sass-loader"
      }
    ]
  },
  {
    "use": [
      {
        "options": {
          "id": 1,
          "omit": 1,
          "remove": true
        },
        "ident": "ref--8-0",
        "loader": "c:\\Apache24\\htdocs\\evai\\node_modules\\extract-text-webpack-plugin\\dist\\loader.js"
      },
      {
        "loader": "style-loader"
      },
      {
        "loader": "css-loader"
      },
      {
        "options": {
          "plugins": [
            null
          ]
        },
        "ident": "ref--8-3",
        "loader": "postcss-loader"
      },
      {
        "options": {
          "sassOptions": {
            "precision": 8,
            "outputStyle": "expanded",
            "indentedSyntax": true
          },
          "implementation": {
            "info": "dart-sass\t1.23.6\t(Sass Compiler)\t[Dart]\ndart2js\t2.6.1\t(Dart Compiler)\t[Dart]",
            "types": {}
          }
        },
        "ident": "ref--8-4",
        "loader": "sass-loader"
      }
    ]
  },
  {
    "use": [
      {
        "options": {
          "id": 1,
          "omit": 1,
          "remove": true
        },
        "ident": "ref--9-0",
        "loader": "c:\\Apache24\\htdocs\\evai\\node_modules\\extract-text-webpack-plugin\\dist\\loader.js"
      },
      {
        "loader": "style-loader"
      },
      {
        "loader": "css-loader"
      },
      {
        "options": {
          "plugins": [
            null
          ]
        },
        "ident": "ref--9-3",
        "loader": "postcss-loader"
      },
      {
        "loader": "less-loader"
      }
    ]
  },
  {
    "use": [
      {
        "options": {
          "id": 1,
          "omit": 1,
          "remove": true
        },
        "ident": "ref--10-0",
        "loader": "c:\\Apache24\\htdocs\\evai\\node_modules\\extract-text-webpack-plugin\\dist\\loader.js"
      },
      {
        "loader": "style-loader"
      },
      {
        "loader": "css-loader"
      },
      {
        "options": {
          "plugins": [
            null
          ]
        },
        "ident": "ref--10-3",
        "loader": "postcss-loader"
      },
      {
        "loader": "stylus-loader"
      }
    ]
  },
  {
    "use": [
      {
        "loader": "html-loader"
      }
    ]
  },
  {
    "use": [
      {
        "options": {
          "publicPath": "/"
        },
        "ident": "ref--1-0",
        "loader": "file-loader"
      },
      {
        "options": {
          "enabled": true,
          "gifsicle": {},
          "mozjpeg": {},
          "optipng": {},
          "svgo": {}
        },
        "ident": "ref--1-1",
        "loader": "img-loader"
      }
    ]
  },
  {
    "use": [
      {
        "options": {
          "publicPath": "/"
        },
        "ident": "ref--2",
        "loader": "file-loader"
      }
    ]
  },
  {
    "use": [
      {
        "options": {
          "name": "[name].[ext]?[hash]",
          "publicPath": "/"
        },
        "ident": "ref--3",
        "loader": "file-loader"
      }
    ]
  },
  {
    "use": [
      {
        "options": {
          "presets": [
            "c:\\Apache24\\htdocs\\evai\\node_modules\\@babel\\preset-env\\lib\\index.js"
          ],
          "plugins": [
            "c:\\Apache24\\htdocs\\evai\\node_modules\\@babel\\plugin-syntax-dynamic-import\\lib\\index.js",
            "c:\\Apache24\\htdocs\\evai\\node_modules\\@babel\\plugin-proposal-object-rest-spread\\lib\\index.js",
            [
              "c:\\Apache24\\htdocs\\evai\\node_modules\\@babel\\plugin-transform-runtime\\lib\\index.js",
              {
                "helpers": false
              }
            ]
          ],
          "cacheDirectory": true
        },
        "ident": "ref--4-0",
        "loader": "babel-loader"
      }
    ]
  },
  {
    "use": [
      {
        "options": {
          "id": 1,
          "omit": 1,
          "remove": true
        },
        "ident": "ref--5-0",
        "loader": "c:\\Apache24\\htdocs\\evai\\node_modules\\extract-text-webpack-plugin\\dist\\loader.js"
      },
      {
        "loader": "style-loader"
      },
      {
        "options": {
          "url": true,
          "sourceMap": false,
          "importLoaders": 1
        },
        "ident": "ref--5-2",
        "loader": "css-loader"
      },
      {
        "options": {
          "sourceMap": true,
          "ident": "postcss0",
          "plugins": [
            null
          ]
        },
        "ident": "postcss0",
        "loader": "postcss-loader"
      },
      {
        "options": {
          "sourceMap": true,
          "engine": "rework"
        },
        "ident": "ref--5-4",
        "loader": "resolve-url-loader"
      },
      {
        "options": {
          "sassOptions": {
            "precision": 8,
            "outputStyle": "expanded"
          },
          "implementation": {
            "info": "node-sass\t4.12.0\t(Wrapper)\t[JavaScript]\r\nlibsass  \t3.5.4\t(Sass Compiler)\t[C/C++]",
            "types": {},
            "TRUE": {},
            "FALSE": {},
            "NULL": {}
          },
          "sourceMap": true
        },
        "ident": "ref--5-5",
        "loader": "sass-loader"
      }
    ]
  },
  {
    "use": [
      {
        "options": {
          "id": 1,
          "omit": 1,
          "remove": true
        },
        "ident": "ref--6-0",
        "loader": "c:\\Apache24\\htdocs\\evai\\node_modules\\extract-text-webpack-plugin\\dist\\loader.js"
      },
      {
        "loader": "style-loader"
      },
      {
        "options": {
          "importLoaders": 1
        },
        "ident": "ref--6-2",
        "loader": "css-loader"
      },
      {
        "options": {
          "plugins": [
            null
          ]
        },
        "ident": "ref--6-3",
        "loader": "postcss-loader"
      }
    ]
  },
  {
    "use": [
      {
        "options": {
          "id": 1,
          "omit": 1,
          "remove": true
        },
        "ident": "ref--7-0",
        "loader": "c:\\Apache24\\htdocs\\evai\\node_modules\\extract-text-webpack-plugin\\dist\\loader.js"
      },
      {
        "loader": "style-loader"
      },
      {
        "loader": "css-loader"
      },
      {
        "options": {
          "plugins": [
            null
          ]
        },
        "ident": "ref--7-3",
        "loader": "postcss-loader"
      },
      {
        "options": {
          "sassOptions": {
            "precision": 8,
            "outputStyle": "expanded"
          },
          "implementation": {
            "info": "dart-sass\t1.23.6\t(Sass Compiler)\t[Dart]\ndart2js\t2.6.1\t(Dart Compiler)\t[Dart]",
            "types": {}
          }
        },
        "ident": "ref--7-4",
        "loader": "sass-loader"
      }
    ]
  },
  {
    "use": [
      {
        "options": {
          "id": 1,
          "omit": 1,
          "remove": true
        },
        "ident": "ref--8-0",
        "loader": "c:\\Apache24\\htdocs\\evai\\node_modules\\extract-text-webpack-plugin\\dist\\loader.js"
      },
      {
        "loader": "style-loader"
      },
      {
        "loader": "css-loader"
      },
      {
        "options": {
          "plugins": [
            null
          ]
        },
        "ident": "ref--8-3",
        "loader": "postcss-loader"
      },
      {
        "options": {
          "sassOptions": {
            "precision": 8,
            "outputStyle": "expanded",
            "indentedSyntax": true
          },
          "implementation": {
            "info": "dart-sass\t1.23.6\t(Sass Compiler)\t[Dart]\ndart2js\t2.6.1\t(Dart Compiler)\t[Dart]",
            "types": {}
          }
        },
        "ident": "ref--8-4",
        "loader": "sass-loader"
      }
    ]
  },
  {
    "use": [
      {
        "options": {
          "id": 1,
          "omit": 1,
          "remove": true
        },
        "ident": "ref--9-0",
        "loader": "c:\\Apache24\\htdocs\\evai\\node_modules\\extract-text-webpack-plugin\\dist\\loader.js"
      },
      {
        "loader": "style-loader"
      },
      {
        "loader": "css-loader"
      },
      {
        "options": {
          "plugins": [
            null
          ]
        },
        "ident": "ref--9-3",
        "loader": "postcss-loader"
      },
      {
        "loader": "less-loader"
      }
    ]
  },
  {
    "use": [
      {
        "options": {
          "id": 1,
          "omit": 1,
          "remove": true
        },
        "ident": "ref--10-0",
        "loader": "c:\\Apache24\\htdocs\\evai\\node_modules\\extract-text-webpack-plugin\\dist\\loader.js"
      },
      {
        "loader": "style-loader"
      },
      {
        "loader": "css-loader"
      },
      {
        "options": {
          "plugins": [
            null
          ]
        },
        "ident": "ref--10-3",
        "loader": "postcss-loader"
      },
      {
        "loader": "stylus-loader"
      }
    ]
  },
  {
    "use": [
      {
        "loader": "c:\\Apache24\\htdocs\\evai\\node_modules\\vuetify-loader\\lib\\loader.js",
        "options": {
          "match": [],
          "attrsMatch": []
        }
      },
      {
        "options": {},
        "ident": "vue-loader-options",
        "loader": "vue-loader"
      }
    ]
  }
]
```

**Pull request merged**
